#!/usr/bin/env python3
"""
Generate one VHS theme snippet per Ground Control theme.

The terminal VHS records into has its own colours, entirely separate from the
palette the TUI paints with. If the two disagree even slightly, the frame gets
a visible seam where the app's background meets the terminal's. So instead of
picking the nearest VHS built-in theme by name, derive the terminal theme from
the same JSON the app reads.

    demo/gen_theme_tapes.py            # writes demo/tapes/themes/<theme>.tape

Each generated file is a fragment, meant to be pulled in from a real tape:

    Source demo/tapes/themes/gruvbox.tape

Re-run this after adding or editing a theme under ground_control/themes/.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from prepare_config import build_vhs_theme  # noqa: E402
from ground_control.utils.colors import THEMES_DIR, load_theme  # noqa: E402

OUT_DIR = HERE / "tapes" / "themes"


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    names = sorted(p.stem for p in THEMES_DIR.glob("*.json"))
    if not names:
        print(f"gen_theme_tapes: no themes found in {THEMES_DIR}",
              file=sys.stderr)
        return 1

    for name in names:
        colors = load_theme(name)
        if not colors:
            print(f"gen_theme_tapes: could not read theme {name!r}",
                  file=sys.stderr)
            continue
        (OUT_DIR / f"{name}.tape").write_text(
            f"# Terminal colours matching the '{name}' Ground Control theme.\n"
            f"# Generated by demo/gen_theme_tapes.py -- do not edit by hand.\n"
            f"{build_vhs_theme(colors)}\n")

    print(f"gen_theme_tapes: wrote {len(names)} theme fragments to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
